spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 
            client-secret: 
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-okd8043x1ty33f1p.us.auth0.com/
